TIHabModuleTemplate.displayName.ExoticMatterFuser=奇异物质融合器
TIHabModuleTemplate.description.ExoticMatterFuser=产生奇异物质的粒子加速器。
TIHabModuleTemplate.displayName.AdvancedExoticMatterFuser=改进型奇异物质融合器
TIHabModuleTemplate.description.AdvancedExoticMatterFuser=产生奇异物质的改进型粒子加速器。
TIHabModuleTemplate.displayName.AdvancedSupercollider=改进型超级对撞机
TIHabModuleTemplate.description.AdvancedSupercollider=能够产生大量反物质的改进型超级对撞机。
TIHabModuleTemplate.displayName.OversizedSupercollider=先进超级对撞机
TIHabModuleTemplate.description.OversizedSupercollider=能够产生巨量反物质的先进超级对撞机。
TIHabModuleTemplate.displayName.Synthesiser=合成器
TIHabModuleTemplate.description.Synthesiser=满足设施基本需求的能量物质转换器。
TIHabModuleTemplate.displayName.E-AMFusionReactorFarm=奇异-反物质反应堆
TIHabModuleTemplate.description.E-AMFusionReactorFarm=能够产生大量电力的巨型奇异-反物质反应堆。
TIHabModuleTemplate.displayName.ResearchLab=研究实验室
TIHabModuleTemplate.description.ResearchLab=研究实验室

TIHabModuleTemplate.displayName.AdvancedAutomatedMiningComplex=改进型自动化采矿综合体
TIHabModuleTemplate.description.AdvancedAutomatedMiningComplex=改进型自动化采矿综合体
TIHabModuleTemplate.displayName.AdvancedOutpostMiningComplex=改进型前哨采矿综合体
TIHabModuleTemplate.description.AdvancedOutpostMiningComplex=改进型前哨采矿综合体
TIHabModuleTemplate.displayName.AdvancedSettlementMiningComplex=改进型定居点采矿综合体
TIHabModuleTemplate.description.AdvancedSettlementMiningComplex=改进型定居点采矿综合体
TIHabModuleTemplate.displayName.AdvancedColonyMiningComplex=改进型殖民地采矿综合体
TIHabModuleTemplate.description.AdvancedColonyMiningComplex=改进型殖民地采矿综合体
TIHabModuleTemplate.displayName.AdvancedAutomatedMiningComplexII=先进自动化采矿综合体
TIHabModuleTemplate.description.AdvancedAutomatedMiningComplexII=先进自动化采矿综合体
TIHabModuleTemplate.displayName.AdvancedOutpostMiningComplexII=先进前哨采矿综合体
TIHabModuleTemplate.description.AdvancedOutpostMiningComplexII=先进前哨采矿综合体
TIHabModuleTemplate.displayName.AdvancedSettlementMiningComplexII=先进定居点采矿综合体
TIHabModuleTemplate.description.AdvancedSettlementMiningComplexII=先进定居点采矿综合体
TIHabModuleTemplate.displayName.AdvancedColonyMiningComplexII=先进殖民地采矿综合体
TIHabModuleTemplate.description.AdvancedColonyMiningComplexII=先进殖民地采矿综合体

TIHabModuleTemplate.displayName.Irradiator=辐照器
TIHabModuleTemplate.description.Irradiator=将金属和贵金属转化为裂变物。
TIHabModuleTemplate.displayName.AdvancedNanofacturingComplex=先进纳米制造综合体
TIHabModuleTemplate.description.AdvancedNanofacturingComplex=先进的纳米工厂。
TIHabModuleTemplate.displayName.EAMSolarFarm=EM/AM太阳能农场阵列
TIHabModuleTemplate.description.EAMSolarFarm=利用反物质和奇异物质提高发电量的先进太阳能农场。
TIHabModuleTemplate.displayName.Noblelizer=贵金属转化器
TIHabModuleTemplate.description.Noblelizer=利用一些反物质和奇异物质，将金属和裂变物转化为贵金属。

TIHabModuleTemplate.displayName.AdministrationController=改进型管理综合体
TIHabModuleTemplate.description.AdministrationController=用于栖息地的大型管理中心。
TIHabModuleTemplate.displayName.AdministrationCenter=先进管理综合体
TIHabModuleTemplate.description.AdministrationCenter=用于栖息地的更大规模管理中心。

TIHabModuleTemplate.displayName.WaterMine2=基础深水井
TIHabModuleTemplate.description.WaterMine2=供水的井。
TIHabModuleTemplate.displayName.WaterMine3=深水井
TIHabModuleTemplate.description.WaterMine3=供水的大型井。
TIHabModuleTemplate.displayName.WaterMine4=改进型深水井
TIHabModuleTemplate.description.WaterMine4=供水的更大规模井。
TIHabModuleTemplate.displayName.WaterMine5=先进深水井
TIHabModuleTemplate.description.WaterMine5=供水的更大规模井。

TIHabModuleTemplate.displayName.VolatilesMine2=基础深核挥发物矿
TIHabModuleTemplate.description.VolatilesMine2=供应挥发物的矿。
TIHabModuleTemplate.displayName.VolatilesMine3=深核挥发物矿
TIHabModuleTemplate.description.VolatilesMine3=供应挥发物的深矿。
TIHabModuleTemplate.displayName.VolatilesMine4=改进型深核挥发物矿
TIHabModuleTemplate.description.VolatilesMine4=供应挥发物的更深矿。
TIHabModuleTemplate.displayName.VolatilesMine5=先进深核挥发物矿
TIHabModuleTemplate.description.VolatilesMine5=供应挥发物的更深矿。

TIHabModuleTemplate.displayName.MetalMine2=基础深核金属矿
TIHabModuleTemplate.description.MetalMine2=供应挥发物的矿。
TIHabModuleTemplate.displayName.MetalMine3=深核金属矿
TIHabModuleTemplate.description.MetalMine3=供应挥发物的深矿。
TIHabModuleTemplate.displayName.MetalMine4=改进型深核金属矿
TIHabModuleTemplate.description.MetalMine4=供应挥发物的更深矿。
TIHabModuleTemplate.displayName.MetalMine5=先进深核金属矿
TIHabModuleTemplate.description.MetalMine5=供应挥发物的更深矿。

TIHabModuleTemplate.displayName.NobleMine2=基础深核贵金属矿
TIHabModuleTemplate.description.NobleMine2=供应挥发物的矿。
TIHabModuleTemplate.displayName.NobleMine3=深核贵金属矿
TIHabModuleTemplate.description.NobleMine3=供应挥发物的深矿。
TIHabModuleTemplate.displayName.NobleMine4=改进型深核贵金属矿
TIHabModuleTemplate.description.NobleMine4=供应挥发物的更深矿。
TIHabModuleTemplate.displayName.NobleMine5=先进深核贵金属矿
TIHabModuleTemplate.description.NobleMine5=供应挥发物的更深矿。

TIHabModuleTemplate.displayName.FissilesMine2=基础深核裂变物矿
TIHabModuleTemplate.description.FissilesMine2=供应裂变物的矿。
TIHabModuleTemplate.displayName.FissilesMine3=深核裂变物矿
TIHabModuleTemplate.description.FissilesMine3=供应裂变物的深矿。
TIHabModuleTemplate.displayName.FissilesMine4=改进型深核裂变物矿
TIHabModuleTemplate.description.FissilesMine4=供应裂变物的更深矿。
TIHabModuleTemplate.displayName.FissilesMine5=先进深核裂变物矿
TIHabModuleTemplate.description.FissilesMine5=供应裂变物的更深矿。

TIHabModuleTemplate.displayName.CivilianMegaComplex=民用大型综合体
TIHabModuleTemplate.description.CivilianMegaComplex=先进的住房综合体，容纳相当于一个小城市的人员。
TIHabModuleTemplate.displayName.Replicators=民用复制机综合体
TIHabModuleTemplate.description.Replicators=为栖息地居民提供食物的复制机。
