TIHabModuleTemplate.displayName.ExoticMatterFuser=奇异物质融合器
TIHabModuleTemplate.description.ExoticMatterFuser=产生奇异物质的粒子加速器。
TIHabModuleTemplate.displayName.AdvancedExoticMatterFuser=改进型奇异物质融合器
TIHabModuleTemplate.description.AdvancedExoticMatterFuser=产生奇异物质的改进型粒子加速器。
TIHabModuleTemplate.displayName.AdvancedSupercollider=改进型超级对撞机
TIHabModuleTemplate.description.AdvancedSupercollider=产生更大量反物质的改进型超级对撞机。
TIHabModuleTemplate.displayName.OversizedSupercollider=先进超级对撞机
TIHabModuleTemplate.description.OversizedSupercollider=产生巨量反物质的先进超级对撞机。
TIHabModuleTemplate.displayName.Synthesiser=合成器
TIHabModuleTemplate.description.Synthesiser=满足设施基本需求的能量-物质转换器。
TIHabModuleTemplate.displayName.E-AMFusionReactorFarm=正反物质反应堆
TIHabModuleTemplate.description.E-AMFusionReactorFarm=产生巨大能量的巨型奇异-反物质反应堆。
TIHabModuleTemplate.displayName.ResearchLab=研究实验室
TIHabModuleTemplate.description.ResearchLab=研究实验室

TIHabModuleTemplate.displayName.AdvancedAutomatedMiningComplex=改进型自动化采矿综合设施
TIHabModuleTemplate.description.AdvancedAutomatedMiningComplex=改进型自动化采矿综合设施
TIHabModuleTemplate.displayName.AdvancedOutpostMiningComplex=改进型前哨采矿综合设施
TIHabModuleTemplate.description.AdvancedOutpostMiningComplex=改进型前哨采矿综合设施
TIHabModuleTemplate.displayName.AdvancedSettlementMiningComplex=改进型定居点采矿综合设施
TIHabModuleTemplate.description.AdvancedSettlementMiningComplex=改进型定居点采矿综合设施
TIHabModuleTemplate.displayName.AdvancedColonyMiningComplex=改进型殖民地采矿综合设施
TIHabModuleTemplate.description.AdvancedColonyMiningComplex=改进型殖民地采矿综合设施
TIHabModuleTemplate.displayName.AdvancedAutomatedMiningComplexII=先进自动化采矿综合设施
TIHabModuleTemplate.description.AdvancedAutomatedMiningComplexII=先进自动化采矿综合设施
TIHabModuleTemplate.displayName.AdvancedOutpostMiningComplexII=先进前哨采矿综合设施
TIHabModuleTemplate.description.AdvancedOutpostMiningComplexII=先进前哨采矿综合设施
TIHabModuleTemplate.displayName.AdvancedSettlementMiningComplexII=先进定居点采矿综合设施
TIHabModuleTemplate.description.AdvancedSettlementMiningComplexII=先进定居点采矿综合设施
TIHabModuleTemplate.displayName.AdvancedColonyMiningComplexII=先进殖民地采矿综合设施
TIHabModuleTemplate.description.AdvancedColonyMiningComplexII=先进殖民地采矿综合设施
TIHabModuleTemplate.displayName.Irradiator=辐照器
TIHabModuleTemplate.description.Irradiator=将金属和贵金属转化为裂变物质
TIHabModuleTemplate.displayName.AdvancedNanofacturingComplex=先进纳米制造综合设施
TIHabModuleTemplate.description.AdvancedNanofacturingComplex=先进的纳米工厂
TIHabModuleTemplate.displayName.EAMSolarFarm=正反物质太阳能阵列
TIHabModuleTemplate.description.EAMSolarFarm=利用反物质和奇异物质提高发电量的先进太阳能发电场。

TIHabModuleTemplate.displayName.Noblelizer=贵金属转化器
TIHabModuleTemplate.description.Noblelizer=利用少量反物质和奇异物质，将金属和裂变物质转化为贵金属

TIHabModuleTemplate.displayName.AdministrationController=改进型行政综合设施
TIHabModuleTemplate.description.AdministrationController=用于居住区的大型管理中心。

TIHabModuleTemplate.displayName.AdministrationCenter=先进行政综合设施
TIHabModuleTemplate.description.AdministrationCenter=用于居住区的更大规模管理中心。

TIHabModuleTemplate.displayName.WaterMine2=基础深水井
TIHabModuleTemplate.description.WaterMine2=供水的井。
TIHabModuleTemplate.displayName.WaterMine3=深水井
TIHabModuleTemplate.description.WaterMine3=供水的大型水井。
TIHabModuleTemplate.displayName.WaterMine4=改进型深水井
TIHabModuleTemplate.description.WaterMine4=供水的更大水井。
TIHabModuleTemplate.displayName.WaterMine5=先进深水井
TIHabModuleTemplate.description.WaterMine5=供水的超大水井。

TIHabModuleTemplate.displayName.VolatilesMine2=基础深地挥发物矿场
TIHabModuleTemplate.description.VolatilesMine2=供应挥发物的矿场。
TIHabModuleTemplate.displayName.VolatilesMine3=深地挥发物矿场
TIHabModuleTemplate.description.VolatilesMine3=供应挥发物的深部矿场。
TIHabModuleTemplate.displayName.VolatilesMine4=改进型深地挥发物矿场
TIHabModuleTemplate.description.VolatilesMine4=供应挥发物的更深矿场。
TIHabModuleTemplate.displayName.VolatilesMine5=先进深地挥发物矿场
TIHabModuleTemplate.description.VolatilesMine5=供应挥发物的极深矿场。

TIHabModuleTemplate.displayName.MetalMine2=基础深地金属矿场
TIHabModuleTemplate.description.MetalMine2=供应挥发物的矿场。
TIHabModuleTemplate.displayName.MetalMine3=深地金属矿场
TIHabModuleTemplate.description.MetalMine3=供应挥发物的深部矿场。
TIHabModuleTemplate.displayName.MetalMine4=改进型深地金属矿场
TIHabModuleTemplate.description.MetalMine4=供应挥发物的更深矿场。
TIHabModuleTemplate.displayName.MetalMine5=先进深地金属矿场
TIHabModuleTemplate.description.MetalMine5=供应挥发物的极深矿场。

TIHabModuleTemplate.displayName.NobleMine2=基础深地贵金属矿场
TIHabModuleTemplate.description.NobleMine2=供应挥发物的矿场。
TIHabModuleTemplate.displayName.NobleMine3=深地贵金属矿场
TIHabModuleTemplate.description.NobleMine3=供应挥发物的深部矿场。
TIHabModuleTemplate.displayName.NobleMine4=改进型深地贵金属矿场
TIHabModuleTemplate.description.NobleMine4=供应挥发物的更深矿场。
TIHabModuleTemplate.displayName.NobleMine5=先进深地贵金属矿场
TIHabModuleTemplate.description.NobleMine5=供应挥发物的极深矿场。

TIHabModuleTemplate.displayName.FissilesMine2=基础深地裂变矿场
TIHabModuleTemplate.description.FissilesMine2=供应裂变物质的矿场。
TIHabModuleTemplate.displayName.FissilesMine3=深地裂变矿场
TIHabModuleTemplate.description.FissilesMine3=供应裂变物质的深部矿场。
TIHabModuleTemplate.displayName.FissilesMine4=改进型深地裂变矿场
TIHabModuleTemplate.description.FissilesMine4=供应裂变物质的更深矿场。
TIHabModuleTemplate.displayName.FissilesMine5=先进深地裂变矿场
TIHabModuleTemplate.description.FissilesMine5=供应裂变物质的极深矿场。
