TIProjectTemplate.displayName.Project_EAMFusionReactorFarm=奇异-反物质反应堆
TIProjectTemplate.summary.Project_EAMFusionReactorFarm=<habmodule>
TIProjectTemplate.description.Project_EAMFusionReactorFarm=利用反物质-奇异物质反应产生电力的大型反应堆。

TIProjectTemplate.displayName.Project_MCU0=降低信号特征
TIProjectTemplate.summary.Project_MCU0=我们可以降低太空舰船和空间站的信号特征。
TIProjectTemplate.description.Project_MCU0=利用常见的隐形和伪装原理，我们可以减少太空活动中的可见信号特征，从而降低外星人报复的可能性。

TIProjectTemplate.displayName.Project_MCU1=隐蔽信号特征
TIProjectTemplate.summary.Project_MCU1=我们可以进一步降低太空舰船和空间站的信号特征。
TIProjectTemplate.description.Project_MCU1=利用精密的隐形和伪装原理，我们可以进一步减少太空活动中的可见信号特征，从而降低外星人报复的可能性。

TIProjectTemplate.displayName.Project_Synthesiser=合成器
TIProjectTemplate.summary.Project_Synthesiser=<habmodule>

TIProjectTemplate.displayName.Project_BSuperCollider=改进型超级对撞机
TIProjectTemplate.summary.Project_BSuperCollider=<habmodule>

TIProjectTemplate.displayName.Project_Sniffing=信息素分析
TIProjectTemplate.summary.Project_Sniffing=使我们能够从外星人的信息素排放中获取关于其态度的信息。
TIProjectTemplate.description.Project_Sniffing=通过分析我们找到的信息素，更新外星威胁评估。

TIProjectTemplate.displayName.Project_OSSuperCollider=先进超级对撞机
TIProjectTemplate.summary.Project_OSSuperCollider=<habmodule>

TIProjectTemplate.displayName.Project_EMMassFuser=先进奇异物质融合器
TIProjectTemplate.summary.Project_EMMassFuser=<habmodule>

TIProjectTemplate.displayName.Project_EM_Fuser=奇异物质融合器
TIProjectTemplate.summary.Project_EM_Fuser=<habmodule>

TIProjectTemplate.displayName.Project_PB4=等离子炮台 MKIV
TIProjectTemplate.summary.Project_PB4=<shipmodule>

TIProjectTemplate.displayName.Project_HPB4=重型等离子炮台 MKIV
TIProjectTemplate.summary.Project_HPB4=<shipmodule>

TIProjectTemplate.displayName.Project_PC4=重型等离子加农炮 MKIV
TIProjectTemplate.summary.Project_PC4=<shipmodule>

TIProjectTemplate.displayName.Project_HPC4=超重型等离子加农炮 MKIV
TIProjectTemplate.summary.Project_HPC4=<shipmodule>

TIProjectTemplate.displayName.Project_PB5=等离子炮台 MKV
TIProjectTemplate.summary.Project_PB5=<shipmodule>

TIProjectTemplate.displayName.Project_HPB5=重型等离子炮台 MKV
TIProjectTemplate.summary.Project_HPB5=<shipmodule>

TIProjectTemplate.displayName.Project_PC5=重型等离子加农炮 MKV
TIProjectTemplate.summary.Project_PC5=<shipmodule>

TIProjectTemplate.displayName.Project_HPC5=超重型等离子加农炮 MKV
TIProjectTemplate.summary.Project_HPC5=<shipmodule>

TIProjectTemplate.displayName.Project_ResearchLab=研究实验室
TIProjectTemplate.summary.Project_ResearchLab=<habmodule>

TIProjectTemplate.displayName.Project_AdvancedSpaceExploitationStudies=先进空间开发研究
TIProjectTemplate.summary.Project_AdvancedSpaceExploitationStudies=我们进一步提升在其他星球上寻找最佳采矿地点能力。
TIProjectTemplate.description.Project_AdvancedSpaceExploitationStudies=先进空间开发研究

TIProjectTemplate.displayName.Project_AdvancedAutomatedMiningComplex=改进型自动化采矿综合体
TIProjectTemplate.summary.Project_AdvancedAutomatedMiningComplex=<habmodule>
TIProjectTemplate.description.Project_AdvancedAutomatedMiningComplex=使用反物质为更高效的钻探设备提供动力的改进型自动化采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedOutpostMiningComplex=改进型采矿综合体
TIProjectTemplate.summary.Project_AdvancedOutpostMiningComplex=<habmodule>
TIProjectTemplate.description.Project_AdvancedOutpostMiningComplex=使用反物质为更高效的钻探设备提供动力的改进型采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedSettlementMiningComplex=改进型定居点采矿综合体
TIProjectTemplate.summary.Project_AdvancedSettlementMiningComplex=<habmodule>
TIProjectTemplate.description.Project_AdvancedSettlementMiningComplex=使用反物质为更高效的钻探设备提供动力的改进型定居点采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedColonyMiningComplex=改进型殖民地采矿综合体
TIProjectTemplate.summary.Project_AdvancedColonyMiningComplex=<habmodule>
TIProjectTemplate.description.Project_AdvancedColonyMiningComplex=使用反物质为更高效的钻探设备提供动力的改进型殖民地采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedAutomatedMiningComplexII=先进自动化采矿综合体
TIProjectTemplate.summary.Project_AdvancedAutomatedMiningComplexII=<habmodule>
TIProjectTemplate.description.Project_AdvancedAutomatedMiningComplexII=使用反物质和奇异物质为更高效的钻探设备提供动力的先进自动化采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedOutpostMiningComplexII=先进采矿综合体
TIProjectTemplate.summary.Project_AdvancedOutpostMiningComplexII=<habmodule>
TIProjectTemplate.description.Project_AdvancedOutpostMiningComplexII=使用反物质和奇异物质为更高效的钻探设备提供动力的先进采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedSettlementMiningComplexII=先进定居点采矿综合体
TIProjectTemplate.summary.Project_AdvancedSettlementMiningComplexII=<habmodule>
TIProjectTemplate.description.Project_AdvancedSettlementMiningComplexII=使用反物质和奇异物质为更高效的钻探设备提供动力的先进定居点采矿综合体。

TIProjectTemplate.displayName.Project_AdvancedColonyMiningComplexII=先进殖民地采矿综合体
TIProjectTemplate.summary.Project_AdvancedColonyMiningComplexII=<habmodule>
TIProjectTemplate.description.Project_AdvancedColonyMiningComplexII=使用反物质和奇异物质为更高效的钻探设备提供动力的先进殖民地采矿综合体。

TIProjectTemplate.displayName.Project_ExoticHardening=奇异装甲强化栖息地
TIProjectTemplate.summary.Project_ExoticHardening=奇异装甲强化栖息地
TIProjectTemplate.description.Project_ExoticHardening=利用我们对奇异材料的了解为栖息地加装装甲，使其结构更具抵抗力。

TIProjectTemplate.displayName.Project_ExoticHardeningII=奇异-混合装甲强化栖息地
TIProjectTemplate.summary.Project_ExoticHardeningII=奇异-混合装甲强化栖息地
TIProjectTemplate.description.Project_ExoticHardeningII=利用我们对奇异-混合材料的了解为栖息地加装装甲，使其结构更具抵抗力。

TIProjectTemplate.displayName.Project_Irradiator=金属辐照器
TIProjectTemplate.summary.Project_Irradiator=<habmodule>

TIProjectTemplate.displayName.Project_Noblelizer=金属贵金属转化器
TIProjectTemplate.summary.Project_Noblelizer=<habmodule>

TIProjectTemplate.displayName.Project_Decoys=诱饵
TIProjectTemplate.summary.Project_Decoys=诱饵
TIProjectTemplate.description.Project_Decoys=廉价而坚固的导弹，伤害潜力较小，用于吸引敌方点防御火力。

TIProjectTemplate.displayName.Project_AdvancedHybridArmor=先进混合装甲
TIProjectTemplate.summary.Project_AdvancedHybridArmor=<shipmodule>

TIProjectTemplate.displayName.Project_AdvancedNanofacturingComplex=先进纳米制造综合体
TIProjectTemplate.summary.Project_AdvancedNanofacturingComplex=<habmodule>

TIProjectTemplate.displayName.Project_EAMSolarFarm=EM/AM太阳能农场阵列
TIProjectTemplate.summary.Project_EAMSolarFarm=<habmodule>

TIProjectTemplate.displayName.Project_Lorien=洛里恩计划
TIProjectTemplate.summary.Project_Lorien=旨在延长我们议员寿命的先进计划。

TIProjectTemplate.displayName.Project_AlienHate=外星侵略管理
TIProjectTemplate.summary.Project_AlienHate=我们利用对外星人的理解来缓和他们对我们的侵略。

TIProjectTemplate.displayName.Project_AdministrationController=改进型管理综合体
TIProjectTemplate.summary.Project_AdministrationController=<habmodule>

TIProjectTemplate.displayName.Project_AdministrationCenter=先进管理综合体
TIProjectTemplate.summary.Project_AdministrationCenter=<habmodule>

TIProjectTemplate.displayName.Project_MiningFissiles2=基础深核裂变物矿
TIProjectTemplate.summary.Project_MiningFissiles2=<habmodule>
TIProjectTemplate.displayName.Project_MiningFissiles3=深核裂变物矿
TIProjectTemplate.summary.Project_MiningFissiles3=<habmodule>
TIProjectTemplate.displayName.Project_MiningFissiles4=改进型深核裂变物矿
TIProjectTemplate.summary.Project_MiningFissiles4=<habmodule>
TIProjectTemplate.displayName.Project_MiningFissiles5=先进深核裂变物矿
TIProjectTemplate.summary.Project_MiningFissiles5=<habmodule>

TIProjectTemplate.displayName.Project_MiningNoble2=基础深核贵金属矿
TIProjectTemplate.summary.Project_MiningNoble2=<habmodule>
TIProjectTemplate.displayName.Project_MiningNoble3=深核贵金属矿
TIProjectTemplate.summary.Project_MiningNoble3=<habmodule>
TIProjectTemplate.displayName.Project_MiningNoble4=改进型深核贵金属矿
TIProjectTemplate.summary.Project_MiningNoble4=<habmodule>
TIProjectTemplate.displayName.Project_MiningNoble5=先进深核贵金属矿
TIProjectTemplate.summary.Project_MiningNoble5=<habmodule>

TIProjectTemplate.displayName.Project_MiningMetal2=基础深核金属矿
TIProjectTemplate.summary.Project_MiningMetal2=<habmodule>
TIProjectTemplate.displayName.Project_MiningMetal3=深核金属矿
TIProjectTemplate.summary.Project_MiningMetal3=<habmodule>
TIProjectTemplate.displayName.Project_MiningMetal4=改进型深核金属矿
TIProjectTemplate.summary.Project_MiningMetal4=<habmodule>
TIProjectTemplate.displayName.Project_MiningMetal5=先进深核金属矿
TIProjectTemplate.summary.Project_MiningMetal5=<habmodule>

TIProjectTemplate.displayName.Project_MiningVolatiles2=基础深核挥发物矿
TIProjectTemplate.summary.Project_MiningVolatiles2=<habmodule>
TIProjectTemplate.displayName.Project_MiningVolatiles3=深核挥发物矿
TIProjectTemplate.summary.Project_MiningVolatiles3=<habmodule>
TIProjectTemplate.displayName.Project_MiningVolatiles4=改进型深核挥发物矿
TIProjectTemplate.summary.Project_MiningVolatiles4=<habmodule>
TIProjectTemplate.displayName.Project_MiningVolatiles5=先进深核挥发物矿
TIProjectTemplate.summary.Project_MiningVolatiles5=<habmodule>

TIProjectTemplate.displayName.Project_MiningWater2=基础深水井
TIProjectTemplate.summary.Project_MiningWater2=<habmodule>
TIProjectTemplate.displayName.Project_MiningWater3=深水井
TIProjectTemplate.summary.Project_MiningWater3=<habmodule>
TIProjectTemplate.displayName.Project_MiningWater4=改进型深水井
TIProjectTemplate.summary.Project_MiningWater4=<habmodule>
TIProjectTemplate.displayName.Project_MiningWater5=先进深水井
TIProjectTemplate.summary.Project_MiningWater5=<habmodule>

TIProjectTemplate.displayName.Project_ExoticTorch=奇异-反物质火炬推进器
TIProjectTemplate.summary.Project_ExoticTorch=<shipmodule>
TIProjectTemplate.description.Project_ExoticTorch=我们使用奇异-反物质推进器驱动飞船。

TIProjectTemplate.displayName.Project_ExoticCandle=奇异-反物质烛焰推进器
TIProjectTemplate.summary.Project_ExoticCandle=<shipmodule>
TIProjectTemplate.description.Project_ExoticCandle=我们使用奇异-反物质推进器驱动飞船。

TIProjectTemplate.displayName.Project_EAMShipReactorI=EAM舰船反应堆
TIProjectTemplate.summary.Project_EAMShipReactorI=<shipmodule>
TIProjectTemplate.displayName.Project_EAMShipReactorII=EAM反应堆 II
TIProjectTemplate.summary.Project_EAMShipReactorII=<shipmodule>
TIProjectTemplate.displayName.Project_EAMShipReactorIII=EAM反应堆 III
TIProjectTemplate.summary.Project_EAMShipReactorIII=<shipmodule>

TIProjectTemplate.displayName.Project_ExoticArmy=先进奇异装甲强化陆军
TIProjectTemplate.summary.Project_ExoticArmy=我们为陆军升级先进的奇异混合装甲技术，可减少附近核打击造成的伤害。

TIProjectTemplate.displayName.Project_EAMReactorCivil=民用E/AM反应堆
TIProjectTemplate.summary.Project_EAMReactorCivil=我们允许E/AM反应堆用于民用。

TIProjectTemplate.displayName.Project_MiningFreebies1=基础太空采矿网络管理
TIProjectTemplate.summary.Project_MiningFreebies1=我们找到管理太空采矿网络的方法。

TIProjectTemplate.displayName.Project_MiningFreebies2=太空采矿网络管理
TIProjectTemplate.summary.Project_MiningFreebies2=我们将太空采矿网络管理正式化并简化。

TIProjectTemplate.displayName.Project_MiningFreebies4=改进型太空采矿网络管理
TIProjectTemplate.summary.Project_MiningFreebies4=我们提高了管理更大太空采矿网络的能力。

TIProjectTemplate.displayName.Project_MiningFreebies6=先进太空采矿网络管理
TIProjectTemplate.summary.Project_MiningFreebies6=我们提高了管理更大太空采矿网络的能力。

TIProjectTemplate.displayName.Project_ETendril=改进型奇异尖刺散热器
TIProjectTemplate.summary.Project_ETendril=复制外星舰船上常见的卷须散热器的性能。

TIProjectTemplate.displayName.Project_ETendril2=先进奇异尖刺散热器
TIProjectTemplate.summary.Project_ETendril2=改进了外星舰船上常见的卷须散热器的性能。

TIProjectTemplate.displayName.Project_AgricultureComplex2=民用复制机综合体
TIProjectTemplate.summary.Project_AgricultureComplex2=为栖息地居民提供食物的复制机。

TIProjectTemplate.displayName.Project_CivilianComplex2=民用大型综合体
TIProjectTemplate.summary.Project_CivilianComplex2=先进的住房综合体，容纳相当于一个小城市的人员。
